CREATE DATABASE test_db; 

USE test_db; 

CREATE TABLE ttt ( name VARCHAR(255) NOT NULL );

CHANGE MASTER TO MASTER_HOST='mysqlMaster', MASTER_LOG_FILE='mysql-bin.000003', MASTER_USER='repl', MASTER_PASSWORD='password', MASTER_LOG_POS=157, MASTER_PORT=3306;

START SLAVE;